# Generated by Django 6.0.5 on 2026-06-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic_Tracker', '0005_alter_registration_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
