# Generated by Django 6.0.5 on 2026-06-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medic_Tracker', '0007_logout_search_user_interface'),
    ]

    operations = [
        migrations.DeleteModel(
            name='search',
        ),
    ]
